[tool.poetry]
name = "file_ops"
version = "0.1.0"
description = ""
authors = ["Andrey Melnikov <vafilor@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
cli = "file_ops.cli:cli"

[tool.poetry.dependencies]
python = "^3.13"
click = "^8.1.8"
sqlalchemy = "^2.0.36"
alembic = "^1.14.0"
watchdog = "^6.0.0"


[tool.poetry.group.dev.dependencies]
mypy = {extras = ["faster-cache"], version = "^1.15.0"}
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
disallow_untyped_defs = true
strict_equality = true
enable_error_code = "unused-awaitable, truthy-bool, redundant-self, redundant-expr"