"""Create files table

Revision ID: 3dd77f5e2e4e
Revises:
Create Date: 2025-01-05 21:39:59.868653

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dd77f5e2e4e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("db_created_at", sa.DateTime(), nullable=False),
        sa.Column("db_updated_at", sa.DateTime(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("is_directory", sa.Boolean(), nullable=False),
        sa.Column(
            "status", sa.Enum("BASIC", "HASHING", name="filestatus"), nullable=False
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_files_content_hash"), "files", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_files_path"), "files", ["path"], unique=True)
    op.create_index(op.f("ix_files_status"), "files", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_status"), table_name="files")
    op.drop_index(op.f("ix_files_path"), table_name="files")
    op.drop_index(op.f("ix_files_content_hash"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
